apiVersion: v1
kind: Secret
metadata:
  name: taskline-secrets
type: Opaque
stringData:
  APP_TITLE: Taskline
  APP_USERNAME: ayo
  APP_PASSWORD: Pass
  API: newrwrii3eururRJ9JRNnrj39
  VITE_APP_TITLE: Task Test
  APP_VERSION: 0.1.0
  PORT: "3000"
  APPINSIGHTS_CONNECTION_STRING: ""
