apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskline-backend-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: taskline-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
